"""add operational crm records

Revision ID: 267d23420b6c
Revises: 93b3355df2cc
Create Date: 2026-06-06 20:59:15.020109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '267d23420b6c'
down_revision: Union[str, Sequence[str], None] = '93b3355df2cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('agendou', sa.Boolean(), nullable=False),
    sa.Column('data_agendamento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('compareceu', sa.Boolean(), nullable=False),
    sa.Column('data_comparecimento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comprou', sa.Boolean(), nullable=False),
    sa.Column('data_compra', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valor_venda', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('observacao_resultado', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_outcomes_id'), 'lead_outcomes', ['id'], unique=False)
    op.create_index(op.f('ix_lead_outcomes_lead_id'), 'lead_outcomes', ['lead_id'], unique=True)
    op.create_table('lead_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao_curta', sa.Text(), nullable=True),
    sa.Column('responsavel', sa.String(length=100), nullable=False),
    sa.Column('data_limite', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status_tarefa', sa.String(length=50), nullable=False),
    sa.Column('prioridade', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('concluido_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_tasks_data_limite'), 'lead_tasks', ['data_limite'], unique=False)
    op.create_index(op.f('ix_lead_tasks_id'), 'lead_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_lead_tasks_lead_id'), 'lead_tasks', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_tasks_status_tarefa'), 'lead_tasks', ['status_tarefa'], unique=False)
    op.create_table('loss_reasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('motivo_perda_principal', sa.String(length=255), nullable=False),
    sa.Column('motivo_perda_secundario', sa.String(length=255), nullable=True),
    sa.Column('detalhe_livre', sa.Text(), nullable=True),
    sa.Column('registrado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loss_reasons_id'), 'loss_reasons', ['id'], unique=False)
    op.create_index(op.f('ix_loss_reasons_lead_id'), 'loss_reasons', ['lead_id'], unique=True)
    op.create_index(op.f('ix_loss_reasons_motivo_perda_principal'), 'loss_reasons', ['motivo_perda_principal'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loss_reasons_motivo_perda_principal'), table_name='loss_reasons')
    op.drop_index(op.f('ix_loss_reasons_lead_id'), table_name='loss_reasons')
    op.drop_index(op.f('ix_loss_reasons_id'), table_name='loss_reasons')
    op.drop_table('loss_reasons')
    op.drop_index(op.f('ix_lead_tasks_status_tarefa'), table_name='lead_tasks')
    op.drop_index(op.f('ix_lead_tasks_lead_id'), table_name='lead_tasks')
    op.drop_index(op.f('ix_lead_tasks_id'), table_name='lead_tasks')
    op.drop_index(op.f('ix_lead_tasks_data_limite'), table_name='lead_tasks')
    op.drop_table('lead_tasks')
    op.drop_index(op.f('ix_lead_outcomes_lead_id'), table_name='lead_outcomes')
    op.drop_index(op.f('ix_lead_outcomes_id'), table_name='lead_outcomes')
    op.drop_table('lead_outcomes')
    # ### end Alembic commands ###
