"""add pipeline stage history

Revision ID: 93b3355df2cc
Revises: 9771db181bf4
Create Date: 2026-06-06 20:49:21.650611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93b3355df2cc'
down_revision: Union[str, Sequence[str], None] = '9771db181bf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_stage_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('status_origem', sa.String(length=100), nullable=False),
    sa.Column('status_destino', sa.String(length=100), nullable=False),
    sa.Column('alterado_por', sa.String(length=255), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_stage_history_id'), 'pipeline_stage_history', ['id'], unique=False)
    op.create_index(op.f('ix_pipeline_stage_history_lead_id'), 'pipeline_stage_history', ['lead_id'], unique=False)
    op.create_index(op.f('ix_pipeline_stage_history_status_destino'), 'pipeline_stage_history', ['status_destino'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_stage_history_status_destino'), table_name='pipeline_stage_history')
    op.drop_index(op.f('ix_pipeline_stage_history_lead_id'), table_name='pipeline_stage_history')
    op.drop_index(op.f('ix_pipeline_stage_history_id'), table_name='pipeline_stage_history')
    op.drop_table('pipeline_stage_history')
    # ### end Alembic commands ###
