"""add leads and lead sources tables

Revision ID: 9771db181bf4
Revises: 347dde714f6f
Create Date: 2026-06-06 19:22:17.731330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9771db181bf4'
down_revision: Union[str, Sequence[str], None] = '347dde714f6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=30), nullable=False),
    sa.Column('canal_principal', sa.String(length=100), nullable=False),
    sa.Column('procedimento_entrada', sa.String(length=255), nullable=False),
    sa.Column('objetivo_principal', sa.Text(), nullable=True),
    sa.Column('interesse_principal', sa.String(length=255), nullable=True),
    sa.Column('duvida_principal', sa.Text(), nullable=True),
    sa.Column('conhece_clinica', sa.Boolean(), nullable=False),
    sa.Column('conhece_procedimento', sa.Boolean(), nullable=False),
    sa.Column('ja_fez_estetica', sa.Boolean(), nullable=False),
    sa.Column('historico_estetico_curto', sa.Text(), nullable=True),
    sa.Column('temperatura', sa.String(length=50), nullable=False),
    sa.Column('qualificacao', sa.String(length=50), nullable=False),
    sa.Column('status_atual', sa.String(length=100), nullable=False),
    sa.Column('responsavel_atual', sa.String(length=100), nullable=False),
    sa.Column('resumo_atual', sa.Text(), nullable=True),
    sa.Column('proxima_acao', sa.Text(), nullable=True),
    sa.Column('data_proxima_acao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_nome'), 'leads', ['nome'], unique=False)
    op.create_index(op.f('ix_leads_status_atual'), 'leads', ['status_atual'], unique=False)
    op.create_index(op.f('ix_leads_telefone'), 'leads', ['telefone'], unique=False)
    op.create_table('lead_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('canal', sa.String(length=100), nullable=False),
    sa.Column('origem', sa.String(length=255), nullable=True),
    sa.Column('campanha', sa.String(length=255), nullable=True),
    sa.Column('conjunto', sa.String(length=255), nullable=True),
    sa.Column('anuncio', sa.String(length=255), nullable=True),
    sa.Column('utm_source', sa.String(length=255), nullable=True),
    sa.Column('utm_medium', sa.String(length=255), nullable=True),
    sa.Column('utm_campaign', sa.String(length=255), nullable=True),
    sa.Column('utm_content', sa.String(length=255), nullable=True),
    sa.Column('utm_term', sa.String(length=255), nullable=True),
    sa.Column('landing_origem', sa.String(length=255), nullable=True),
    sa.Column('capturado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_sources_campanha'), 'lead_sources', ['campanha'], unique=False)
    op.create_index(op.f('ix_lead_sources_id'), 'lead_sources', ['id'], unique=False)
    op.create_index(op.f('ix_lead_sources_lead_id'), 'lead_sources', ['lead_id'], unique=True)
    op.create_index(op.f('ix_lead_sources_utm_campaign'), 'lead_sources', ['utm_campaign'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_sources_utm_campaign'), table_name='lead_sources')
    op.drop_index(op.f('ix_lead_sources_lead_id'), table_name='lead_sources')
    op.drop_index(op.f('ix_lead_sources_id'), table_name='lead_sources')
    op.drop_index(op.f('ix_lead_sources_campanha'), table_name='lead_sources')
    op.drop_table('lead_sources')
    op.drop_index(op.f('ix_leads_telefone'), table_name='leads')
    op.drop_index(op.f('ix_leads_status_atual'), table_name='leads')
    op.drop_index(op.f('ix_leads_nome'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
